version: '3.8'

services:
  yttranscript-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: yttranscript-mcp:latest
    container_name: yttranscript-mcp-server
    ports:
      - "8000:8000"
    environment:
      - YT_TRANSCRIPT_SERVER_HOST=0.0.0.0
      - YT_TRANSCRIPT_SERVER_PORT=8000
      - YT_TRANSCRIPT_DEBUG=false
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    # Resource limits for production safety
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Development variant with debug enabled and volume mount
  yttranscript-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: yttranscript-mcp:latest
    container_name: yttranscript-mcp-dev
    ports:
      - "8001:8000"
    environment:
      - YT_TRANSCRIPT_SERVER_HOST=0.0.0.0
      - YT_TRANSCRIPT_SERVER_PORT=8000
      - YT_TRANSCRIPT_DEBUG=true
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount source code for development (comment out for production)
      - ./src:/app/src:ro
    command: ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - dev

networks:
  default:
    name: yttranscript-network